CREATE TABLE IF NOT EXISTS User (
   UserId   INTEGER AUTONUMBER PRIMARY KEY,
   UserName TEXT NOT NULL,
   UserLocation TEXT NOT NULL,
   UserDate DATE NOT NULL,
   ClientId INTEGER NOT NULL,

   CONSTRAINT UserName_Unique UNIQUE (Username)
   FOREIGN KEY (ClientId) REFERENCES Client(ClientId)
);
