class SocketRequest {

  /**
   * Manage a socket.
   * @param {Object} requestSocket Socket generated by Socket.io
   * @returns {Object} SocketRequest instance.
   */
  constructor (requestSocket) {
    this.socketObject = requestSocket;
    this.socketRequestId = requestSocket.client.id;
    this.socketRequestPath = requestSocket.client.request.url;
    this.socketRequestMethod = requestSocket.client.request.method;
    this.socketHandshake = requestSocket.handshake.issued;
  }

  /**
   * Generate a summary about the request.
   * @returns {String} Summary about the request.
   */
  summary () {
    return `${this.socketRequestMethod} -> ${this.socketRequestPath} (${this.socketRequestId})`;
  }

  /**
   * Authenticate a user.
   * @param {Function} requestHandler Custom handler function.
   */
  authenticate (requestHandler) {
    this.socketObject.on('user:send', requestData => requestHandler('Authenticate', requestData));
  }

  /**
   * Report authentication to a user.
   * @param {Object} establishedUser Signed user object.
   */
  authenticated (establishedUser) {
    this.socketObject.emit('user:suc', establishedUser);
  }

  /**
   * Report failed authentication.
   * @param {Error} unauthenticatedReason Reason for failure.
   */
  unauthenticated (unauthenticatedReason) {
    this.socketObject.emit('user:fai', unauthenticatedReason.stack);
  }

  // TODO: JSDoc this.
  register (registerHandler) {
    this.socketObject.on('client:send', registerData => registerHandler('Register', registerData));
  }

  // TODO: JSdoc this.
  registered (registeredUser) {
    if (!registeredUser) {
      this.unregistered({message: "registeredUser was null for some reason."});
    } else {
      this.socketObject.emit('client:suc', registeredUser);
    }
  }

  // TODO: JSdoc this.
  unregistered (unregisteredReason) {
    console.log(unregisteredReason);
    this.socketObject.emit('client:fai', unregisteredReason.message);
  }
}

module.exports = SocketRequest;